### ISSUE TITLE
Page name title (tab name)

### ISSUE THREAD

**Issue by JakePowis** [WebAhead5/CSS-Project-TeamTarzan#2]
https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L6

The title has been left as the default 'Title', which then generates the tab name of Title in the browser. This could be changed to something like 'Team Tarzan Webpage" so that its clearer for the user when tabbed.

**Comment by majdk143** [comment]
Added a proper title "Project TeamTarzan" thank you for finding this issue.
