### ISSUE TITLE
navigation bar, position after clicking and transparency   

### ISSUE THREAD

**Issue by hadikalil** [WebAhead5/CSS-Project-TeamTarzan#4]
Hello Tarzan team 
Note that after clicking on one of the bottoms of the navigation bar the positions are not perfectly positioned.
1- go to team page 
2- click on the navigation bar bottoms:
                 a. about us
                 b. contact us 

expected results:
navigate to the begging of the section that was intended

actual results:
it is not  starting at the begging of the section   
also the transparency of the navigation bar can be miss confusing with the text behind .

**Comment by majdk143** [comment]
Issue was fixed by adding a margin to the top so it sits properly, thank you for pointing this issue out.
