### ISSUE TITLE
[bug] contact form disregarding it's field's values

### ISSUE THREAD

**Issue by MorisR** [WebAhead5/CSS-Project-TeamTarzan#5]
the "contact" form does not transfer the field's content to the mailing app

all content within the following fields are disregarded

- First Name field

- Last Name field

- Email field

- Subject field

**Comment by MorisR** [comment]
**fix suggestion:**

https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L112-L136

 wrap the entire section with a "form" tag and use the <input type="submit"> to submit the form 
instead of the "a" tag used  [here](https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L130-L132)

**Comment by JakePowis** [comment]
Further contact form comments:

#input type - email

https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L124

Currently the input type in the form for email is "text" - if you change this to "email" it will make sure that entries into this field are in email format (eg include @ and .com).

**Comment by JakePowis** [comment]
#required fields

https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L115
https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L120
https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/master/index.html#L123

if you add the word 'required' to the input fields, the user will not be able to submit a form when these fields are empty. Currently you are able to submit a blank form.
