### ISSUE TITLE
using tables in design is depricated 

### ISSUE THREAD

**Issue by okarem** [WebAhead5/CSS-Project-TeamTarzan#8]
using tables for design and formatting is a very old practice, no longer used
i would've used divs and the appropriate css code along with it
if you'd like reading about a technique similar to using tables, a relativity new one is [CSS GRID  ](https://www.w3schools.com/css/css_grid.asp) (simple intro)

**Comment by Marwanrizik91** [comment]
we all agree on that, next time we will use grid indeed. ty
