### ISSUE TITLE
misleading ui

### ISSUE THREAD

**Issue by okarem** [WebAhead5/CSS-Project-TeamTarzan#9]
https://github.com/WebAhead5/CSS-Project-TeamTarzan/blob/981d974bfbc8ab06b11204742ed9fdc586d02350/index.html#L26
changing the whole tab colour but the tab actually working only when pressing the text is a bit misleading making the user wait for a non-loading page ... i would wrap the whole button in an <a>

**Comment by Marwanrizik91** [comment]
resolved, ty for the feedback.
